### ISSUE TITLE
It is dangerous to set /proc/sys/kernel/sched_rt_runtime_us to -1

### ISSUE THREAD

**Issue by deepthi-ps** [rdkcentral/Dobby#272]
From Dobby code :

```
    // the following restores the old skool RT scheduling behaviour, and it's
    // needed to ensure that containered apps can start in RT scheduling mode
    if (!mUtilities->writeTextFile("/proc/sys/kernel/sched_rt_runtime_us", "-1\n",
                                   O_TRUNC | O_WRONLY, 0))
    {
        AI_LOG_FATAL("failed to write to sched_rt_runtime_us file, you may have"
                     " issues starting containers");
    }
```
	
According to this RedHat and other documentation, this is a dangerous thing to do.
Setting the value to -1 means that real-time tasks may use up to 100% of CPU times. This is only adequate when the real-time tasks are well engineered and have no obvious caveats such as unbounded polling loops.

[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_for_real_time/7/html/tuning_guide/real_time_throttling](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_for_real_time/7/html/tuning_guide/real_time_throttling)
https://access.redhat.com/solutions/1604133

Additional note:
In our RDK platforms, we have an AppArmor profile restricting write access inside /proc/sys/kernel/ except for shm* and core*.

**Comment by goruklu** [comment]
thanks @deepthi-ps for raising this concern. We'll review and get back to you.
